language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jose1791/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jose1791/docker-react npm run test